# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lhermann <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/02 23:11:32 by lhermann          #+#    #+#              #
#    Updated: 2016/11/02 23:36:41 by lhermann         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = ft_display_file

all:	$(NAME)

$(NAME) :
			gcc -Wall -Werror -Wextra ft_display_file.c ft.c -o ft_display_file
clean :
			rm -f ft_display_file.o
fclean :
			rm -f $(NAME)
re : fclean all
